name: PR Update

on:
  pull_request_target:
    branches:
      - main
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    name: Run Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Build ossgg
    uses: ./.github/workflows/build-web.yml
    secrets: inherit

  e2e-test:
    name: Run E2E Tests
    uses: ./.github/workflows/playwright.yml
    secrets: inherit

  required:
    needs: [lint, test, build, e2e-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
